services:
    basbacio-payroll:
        container_name: basbacio-payroll
        image: tweaktheboss/basbacio-payroll
        build: 
            dockerfile: ./Dockerfile
        ports:
            - 8181:80
        volumes: 
            - ./:/var/www/html
        restart: always